#184581170 Setup Docker for Backend Application
atlp-rwanda/e-comm-team-amigos-bn pull request #10
Opened 2023-03-06 16:37 UTC by ericndungutse

#### What does this PR do?

Have docker setup for backend API

#### Description of Task to be completed?

Have the following functionality configured

- Running express server using docker compose
- Creating  and running postgres using docker compose

#### How should this be manually tested?

First make sure you have docker installed. In your terminal;

1. After rebasing with default branch
2. Run Docker Desktop
3. Run `docker-compose up -d db` to run postgres container
4. Run `docker-compose logs` to check if database is ready for connection.
5. Run `docker-compose build` to build Docker image.
6. Run `docker-compose up app`

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581170 ](https://www.pivotaltracker.com/story/show/184581170)

2023-03-06 16:43 UTC, wilbrord2 approved these changes
good

2023-03-06 16:53 UTC, 1MuhireDavid approved these changes

2023-03-06 16:58 UTC, AbdulKhaliq59 approved these changes

2023-03-06 17:34 UTC, Habinezajanvier requested changes

2023-03-06 17:34 UTC, Habinezajanvier commented on docker-compose.yml
> +      - DB_HOST=db
Can we pick those data from `.env` rather than hard-coding them in `docker-compose` file

2023-03-06 17:34 UTC, Habinezajanvier commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=test1234
Sensible data should be in `.env`

2023-03-06 17:34 UTC, Habinezajanvier commented on docker-compose.yml
> +
find a way to add volumes tag on app services so that editing in dev mode can be synced in real time with changes in docker

2023-03-08 10:39 UTC, nshutijonathan requested changes
Please squash your commits into one

2023-03-09 11:20 UTC, nshutijonathan approved these changes
LGTM

2023-03-09 11:24 UTC, Habinezajanvier requested changes

2023-03-09 11:24 UTC, Habinezajanvier commented on .env.example
> +>>>>>>> 99a2eca... Revert "chore(docker compose): set up docker compose file"
You didn't finish the rebase

2023-03-09 11:45 UTC, ericndungutse commented on .env.example
> +>>>>>>> 99a2eca... Revert "chore(docker compose): set up docker compose file"
Finished.

2023-03-09 15:28 UTC, Habinezajanvier approved these changes
🥇 LGTM

2023-03-09 15:30 UTC, merged