#184581164 integrating houndci with badge on readme
atlp-rwanda/e-comm-team-amigos-bn pull request #12
Opened 2023-03-07 10:57 UTC by remy-mugisha

#### What does this PR do?
This PR ..........

#### Description of Task to be completed?
- ............
- ............
- ............

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
- ...........
- ...........
- ...........

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- ...........

#### What are the relevant pivotal tracker/Trello stories?

Story ID: ..........

#### Screenshots (if appropriate)

#### Questions:

2023-03-07 12:24 UTC, nshutijonathan requested changes
Rename your commit message to embrace our standard 

you can do this `chore(houndci): added hound-ici`

2023-03-07 13:44 UTC, khevin2 approved these changes

2023-03-07 14:32 UTC, AbdulKhaliq59 approved these changes

2023-03-07 14:39 UTC, Emile-SHUMBUSHO approved these changes

2023-03-07 14:45 UTC, 1MuhireDavid approved these changes

2023-03-13 08:31 UTC, GasanaJr approved these changes

2023-03-16 14:56 UTC, nshutijonathan approved these changes
LGTM

2023-03-16 18:00 UTC, Habinezajanvier requested changes

2023-03-16 18:00 UTC, Habinezajanvier commented on README.md
> +[![HoundCI](https://img.shields.io/badge/houndci-checked-brightgreen.svg)](https://houndci.com)
Please put this checks at the top of document and make sure that none is duplicated

2023-03-22 11:48 UTC, closed without merging