#184581172 feat(user): User Sign Up WIP
atlp-rwanda/e-comm-team-amigos-bn pull request #13
Opened 2023-03-08 11:53 UTC by 1MuhireDavid

#### What does this PR do?
This PR allows enable user to be able to sign up.

#### Description of Task to be completed?
- Create signup endpoint.
- Create router to create user.
- Create a middleware to validate and hash password of the user.
- Verify if the user does not already exist if they exists send a message that a user already exists 

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
- /user/create

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have Postgress and Sequelize installed on local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [ #184581172](https://www.pivotaltracker.com/n/projects/2632829/stories/184629360)

2023-03-09 05:38 UTC, AbdulKhaliq59 approved these changes

2023-03-09 07:24 UTC, Emile-SHUMBUSHO approved these changes

2023-03-09 07:28 UTC, GasanaJr approved these changes

2023-03-09 13:43 UTC, AbdulKhaliq59 approved these changes

2023-03-10 08:57 UTC, nshutijonathan requested changes
- Please you have more than two commits and that is not acceptable 
- Can you attach the screenshot showing passing tests?
- Can you also attach a screenshot showing swagger in action /speaking of user sign up 
- Please also update your readme file and inform non-technical users how your JSON values get passed. check readme of the following repo `https://github.com/atlp-rwanda/e-comm-team-brogrammers-bn`

2023-03-10 08:57 UTC, nshutijonathan commented on .env.example
> +REFRESH_TOKEN_SECRET=a00a248ce550b46b66b08cf5ed597a0b14b1877c02714110bfe402ded54a4a3e76b426c8da9f65726c33dbe83f736ed9d905bafd4a7e942bb0e271bd499a7c6b
I hope these tokens are not valid ones, otherwise, we exposed them to the public.

2023-03-10 08:57 UTC, nshutijonathan commented on src/middleware/authValidation.js
> +    console.log(error);
console.log is for debugging purpose ,remove it here ,It should not be pushed

2023-03-10 13:15 UTC, Habinezajanvier requested changes

2023-03-10 13:15 UTC, Habinezajanvier commented on package.json
> +    "babel": "^6.23.0",
- Remove babel in favor to babel/cli
- Remove also body-parser in favor to express.json()

2023-03-10 13:15 UTC, Habinezajanvier commented on package.json
> +    "rimraf": "^4.1.2",
`rimraf` is installed twice

2023-03-10 13:15 UTC, Habinezajanvier commented on src/app.js
Remain only with `express.json()`

2023-03-10 13:15 UTC, Habinezajanvier commented on src/controllers/authentication.js
> +  if (user) return res.status(400).send("Email address already in use (email)");
Please don't send plain string as response

2023-03-10 14:32 UTC, ericndungutse commented
> #### What does this PR do?
> This PR allows enable user to be able to sign up.
> 
> #### Description of Task to be completed?
> Have the following endpoint working
> `POST /user/create`
> 
> #### How should this be manually tested?
> - Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
> - Switch your working directory cd e-comm-team-amigos-bn
> - Create an .env file and update it with .env-example
> - Install all the dependencies by running npm install
> - Then run the project by typing npm start
> - Using Postman test **user/create** endpoint  
>  by writing POST http://localhost:3000/user/create
> _key_:Context-Type value: application/json
> 
>   
> 
> #### Any background context you want to provide?
> - Have Node Js installed in your local machine
> - Have Postgress and Sequelize installed on local machine
> - Have Postman installed on your local machine
> 
> 
> #### What are the relevant pivotal tracker/Trello stories?
> 
> Story ID: [ #184581172](https://www.pivotaltracker.com/n/projects/2632829/stories/184629360)
> 
> #### Screenshots
> #### documented endponts on swager ui
> ![doc](https://user-images.githubusercontent.com/49757277/224320711-bf4fc660-710b-4bbd-a38d-20e47517ef96.png)
> #### Passed Test
> ![Screenshot 2023-03-10 144628](https://user-images.githubusercontent.com/49757277/224320773-dbd86673-4e27-4d50-8f5c-28ebb0bcff8e.png)

This check is repeared twice. In auth controller and in validation. **let user = await models.User.findOne({ where: { email: req.body.email } }); 
   if (user) return res.status(400).send("Email address already in use (email)");**

2023-03-11 07:54 UTC, Emile-SHUMBUSHO commented
> This check is repeared twice. In auth controller and in validation. **let user = await models.User.findOne({ where: { email: req.body.email } });   if (user) return res.status(400).send("Email address already in use (email)");**

2023-03-13 12:55 UTC, Habinezajanvier approved these changes
👍

2023-03-13 12:56 UTC, merged