#184581175 User Login feature
atlp-rwanda/e-comm-team-amigos-bn pull request #16
Opened 2023-03-09 07:44 UTC by GasanaJr

#### What does this PR do?
This PR adds a login functionality to the application
#### Description of Task to be completed?
- add a login endpoint
- Users should be able to login via email and password
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- switch your working directory `cd e-comm-team-amigos-bn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm start`
#### Test the endpoints using Postman:
- `POST user/login`
#### Any background context you want to provide?
- PostgreSQL installed in your local machine
- Node JS installed in your local machine
#### What are the relevant pivotal tracker stories?
Story ID: [#184581175](https://www.pivotaltracker.com/n/projects/2632829/stories/184581175)

2023-03-11 12:22 UTC, Emile-SHUMBUSHO approved these changes

2023-03-11 13:03 UTC, wilbrord2 approved these changes

2023-03-12 10:40 UTC, ericndungutse approved these changes
LGTM

2023-03-13 08:00 UTC, nshutijonathan requested changes
You have 7 commits messages, can you please narrow them down to 1?

2023-03-13 08:20 UTC, GasanaJr commented
> You have 7 commits messages, can you please narrow them down to 1?
Of the seven commits on this branch, only two belong to me. The other commits came with me rebasing from the Signup branch. I am not sure if squashing them won't lead to any data loss.

2023-03-13 14:16 UTC, Emile-SHUMBUSHO approved these changes

2023-03-13 14:21 UTC, merged