#184581176 Sign with Google
atlp-rwanda/e-comm-team-amigos-bn pull request #17
Opened 2023-03-09 11:28 UTC by khevin2

#### What does this PR do?
- Add `Sign In with Google` functionality
#### Description of Task to be completed?
- Add functionality so that a user can use his/her Google account to Login
- Users should click to link and be redirected to Google sign In page
- After users confirm their identity with Google they are redirected to this app
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- switch your working directory `cd e-comm-team-amigos-bn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm run dev`
#### Test the endpoints using browser:
- Go to [Auth with Google](http://localhost:4000/token/google)
#### Any background context you want to provide?
- PostgreSQL installed in your local machine
- Node JS installed in your local machine
- Have a working `Google` account
#### What are the relevant pivotal tracker stories?
Story ID: [#184581176](https://www.pivotaltracker.com/story/show/184581176)
- #### Screenshots

![Screenshot from 2023-03-14 15-49-17](https://user-images.githubusercontent.com/40208392/225025582-ea514b5f-d0b0-4baf-8d98-8621f799b9c5.png)
![Screenshot from 2023-03-14 16-00-43](https://user-images.githubusercontent.com/40208392/225026079-ffe868b1-7394-4289-8ffd-42b1b6ae1af7.png)

2023-03-10 15:41 UTC, Emile-SHUMBUSHO commented
Fix npm start so that we can be able to run it as we do it with npm run dev.

2023-03-10 15:44 UTC, GasanaJr approved these changes
The code is running perfectly fine for users who are not registered, those who are registered, and for invalid emails. Nice job. However, try to change the PR request body and add all the processes involved in testing your API for example the correct endpoints

2023-03-10 16:16 UTC, GasanaJr reviewed
Perfect. The code is behaving as expected for registered, unregistered, and invalid emails. Good job. However, fix the npm start and in the PR description add the step of checking out to your branch i.e `git checkout`

2023-03-11 12:19 UTC, Emile-SHUMBUSHO approved these changes

2023-03-13 11:26 UTC, 1MuhireDavid approved these changes

2023-03-13 13:14 UTC, ericndungutse approved these changes
LGTM

2023-03-13 19:55 UTC, nshutijonathan requested changes

2023-03-13 19:55 UTC, nshutijonathan commented on src/helpers/google.oath.js
> +    // console.log(profile, "\nAccessToken: ", accessToken, "\nrefreshToken: ", refreshToken)
Don't push commented-out codes

2023-03-14 07:05 UTC, Mystica52 reviewed
can you reslove the conflict from package.json

2023-03-14 12:10 UTC, Habinezajanvier requested changes

2023-03-14 12:10 UTC, Habinezajanvier commented on src/app.js
> +sequelize.authenticate().then(() => console.log("Database connected")).catch((err) => console.error(err));
We don't need console.log in production codes

2023-03-14 12:10 UTC, Habinezajanvier commented on src/app.js
> +}));
Is it a necessity to use cookies ?

2023-03-14 12:10 UTC, Habinezajanvier commented on src/controllers/token.controller.js
> +    res.status(400).json({ message: "Could not complete this process", error: true });
Let's message be used on successful request and then send error for failed request

2023-03-14 12:37 UTC, khevin2 commented on src/app.js
> +}));
> Is it a necessity to use cookies ?

Yes. Since the google user will be tied on `request`, using sessions is the good implementation.

2023-03-14 13:32 UTC, nshutijonathan requested changes
Finally, can you please add relevant screenshots of your task implemented and the test coverage?

2023-03-14 14:06 UTC, khevin2 commented
> Finally, can you please add relevant screenshots of your task implemented and the test coverage?

Done

2023-03-14 15:13 UTC, Habinezajanvier requested changes

2023-03-14 15:13 UTC, Habinezajanvier commented on src/controllers/token.controller.js
> +    }
Please remove all console.log, and make sure that you are sending a good formatted response, not the error object

2023-03-14 17:28 UTC, Habinezajanvier approved these changes
Smells good to me

2023-03-14 17:29 UTC, merged