#184581179 Two Factor Authentication for Sellers
atlp-rwanda/e-comm-team-amigos-bn pull request #18
Opened 2023-03-09 14:10 UTC by wilbrord2

#### What does this PR do?

This PR verify if user is a seller and he/she can login as a seller

#### Description of Task to be completed?

- [ ] A seller will be successfully login with email and password

- [ ] A seller should receive email containing random number for 2FA to verify if he/she is owner of stall.

- [ ] Document feature using swagger.

#### How should this be manually tested?
- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- Switch your working directory `cd e-comm-team-amigos-bn`
- Create an` .env` file and update it with `.env-example`
- Install all the dependencies by running` npm install`
- Then run the project by typing `npm dev` to start server
- Make sure that postman is installed, open postman or any other API testing tool of your choice
- choose route to be `POST`
- Navigate `localhost:3000/user/login`
- Make sure you created account, enter your username and password
- if you are a seller you will receive email containing `OTP (one-time-password) `
- you can use it to successfully login

#### Endpoints to be tested:

- `POST user/login`

#### Any background context you want to provide?

- PostgreSQL installed in your local machine
- Node JS installed in your local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581179](https://www.pivotaltracker.com/story/show/184581179)

2023-03-13 08:02 UTC, nshutijonathan requested changes

2023-03-13 08:02 UTC, nshutijonathan commented on src/tests/auth.test.js
> +    // const timestamp = updatedUser.otpcodeexpiration;
Don't push commented out codes

2023-03-13 08:02 UTC, nshutijonathan commented on src/tests/auth.test.js
> +  //     to: user.email,
commented out codes should not get pushed

2023-03-13 08:30 UTC, GasanaJr requested changes
The feature works as expected, but the circleci tests must still be included. Integrate the tests, and we will be good to go. Also update the body of your PR to include screenshots for swagger and running tests.

2023-03-13 12:58 UTC, 1MuhireDavid approved these changes

2023-03-13 13:14 UTC, Rwibutso approved these changes

2023-03-14 09:35 UTC, GasanaJr requested changes
Solve conflicts you have in develop

2023-03-14 10:05 UTC, AbdulKhaliq59 approved these changes

2023-03-14 10:06 UTC, AbdulKhaliq59 requested changes
Resolve conflict

2023-03-14 10:40 UTC, Emile-SHUMBUSHO approved these changes

2023-03-14 11:40 UTC, GasanaJr approved these changes

2023-03-14 11:46 UTC, AbdulKhaliq59 approved these changes

2023-03-14 13:36 UTC, nshutijonathan commented on src/database/migrations/20230312135251-Users.js
> +    // await queryInterface.addColumn('Users', ' otpcode', {
remove commented out codes here

2023-03-14 13:36 UTC, nshutijonathan commented on src/database/migrations/20230312135251-Users.js
> +    //   type: Sequelize.STRING,
remove commented out codes here

2023-03-14 13:37 UTC, nshutijonathan commented on src/database/migrations/20230312135251-Users.js
> +    // await queryInterface.removeColumn('Users', 'otpcodeexpiration');
commented out codes should not be pushed

2023-03-14 13:38 UTC, nshutijonathan requested changes
Remember to rebase so that the conflicts are gone and then we are good to go

2023-03-14 15:08 UTC, nshutijonathan approved these changes
LGTM

2023-03-14 15:35 UTC, merged