#184581182 set user roles or permissions
atlp-rwanda/e-comm-team-amigos-bn pull request #22
Opened 2023-03-14 23:53 UTC by Emile-SHUMBUSHO

- admin should be able to set roles or permissions
- implement two functions one is for getting users and for setting role
- creates endpoint for getting all users
- creates endpoint for setting user role
- document endpoints using swager ui

[Delivers #184581182]

#### What does this PR do?
This PR implements functionality for the admin to set roles to the other users

#### Description of Task to be completed?
- as admin I should be able to set user permissions
- list all users
- have a user Id and assign a role accordingly
- current user with an admin role status is not allowed to be modified

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
-`localhost:400/user/users`
-`localhost:400/user/id`

#### Any background context you want to provide?
- Have Node Js installed in your local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581182](https://www.pivotaltracker.com/n/projects/2632829/stories/184581182)

#### Screenshots (if appropriate)
swager ui documentation
![image](https://user-images.githubusercontent.com/49757277/225167329-12749f38-3979-412e-9e9e-cfaaad0084cd.png)
#### Questions:

2023-03-17 10:00 UTC, Mystica52 reviewed
resolve the issue in your circle ci

2023-03-17 10:46 UTC, nshutijonathan commented on src/tests/roles.test.js
> +    // expect(res.body.count).to.equal(res.length);
remove commented out codes from your the repo

2023-03-17 10:46 UTC, nshutijonathan reviewed
Remove commented out codes

2023-03-17 12:32 UTC, 1MuhireDavid reviewed
Please remember to edit the PR description and remove the commit message.

2023-03-19 18:44 UTC, GasanaJr requested changes
Is it possible to attach a screenshot of passing tests in the PR body?

2023-03-19 18:49 UTC, wilbrord2 approved these changes

2023-03-19 22:55 UTC, GasanaJr approved these changes
Great Job

2023-03-20 06:32 UTC, AbdulKhaliq59 approved these changes

2023-03-20 07:24 UTC, Habinezajanvier approved these changes
👍

2023-03-20 07:24 UTC, merged