feat(products): update products in seller collection
atlp-rwanda/e-comm-team-amigos-bn pull request #24
Opened 2023-03-15 11:47 UTC by khevin2

#### What does this PR do?
This PR allows a seller/vendor to update products in his/her collection

#### Description of Task to be completed?
- Create product update routes
- Update products in seller collection
- Create docs and tests for the functionalities above.

#### How should this be manually tested?
- Clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- Switch your working directory `cd e-comm-team-amigos-bn`
- Create an `.env` file and update it with `.env-example` file
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`

#### Endpoints to be tested in Postman:
- `/products/{id}` to update a product.

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have Postgres
- API tester like Postman

#### What are the relevant pivotal tracker?

Story ID: [#184581189](https://www.pivotaltracker.com/n/projects/2632829/stories/184581189)

#### Screenshots

2023-03-17 10:42 UTC, nshutijonathan reviewed
Please add relevant screenshoot

2023-03-18 13:45 UTC, Emile-SHUMBUSHO approved these changes

2023-03-18 15:04 UTC, ericndungutse approved these changes
LGTM

2023-03-18 15:16 UTC, wilbrord2 approved these changes

2023-03-18 17:47 UTC, GasanaJr approved these changes

2023-03-20 06:33 UTC, AbdulKhaliq59 approved these changes

2023-03-21 14:14 UTC, nshutijonathan requested changes
Check my comments

2023-03-21 14:14 UTC, nshutijonathan commented on src/routes/auth/index.js
> +// , validate.authorize(['admin', 'vendor', 'normal'])
commented out codes should not be pushed

2023-03-21 14:14 UTC, nshutijonathan commented on src/validations/product.validator.js
> +    res.status(500).json({ errorMessage: "Server error", err });
I would go with `error`:`error.message`  instead of imagining the error

2023-03-21 14:14 UTC, nshutijonathan commented on src/controllers/product.controller.js
> +    res.status(500).json({ error: "Server error", err });
I would go with `error:error.message` instead of imagining the error

2023-03-21 14:14 UTC, nshutijonathan commented on src/controllers/product.controller.js
>      console.error(err);
remove console.log

2023-03-21 14:30 UTC, khevin2 commented
> Check my comments

Resolved

2023-03-21 16:47 UTC, nshutijonathan approved these changes
LGTM

2023-03-24 10:47 UTC, Habinezajanvier approved these changes
👍

2023-03-25 14:25 UTC, merged