feat(add Product): Implement create product endpoint
atlp-rwanda/e-comm-team-amigos-bn pull request #25
Opened 2023-03-15 12:51 UTC by AbdulKhaliq59

#### What does this PR do?
This PR Create/Add Product in seller's collection

#### Description of Task to be completed?
- [ ] Create input validation
- [ ] verify seller's token
- [ ] Create endpoint for creating product
- [ ] Swagger documentation for this this endpoint
- [ ] test For this endpoint

#### How should this be manually tested?
- Clone this repo git clone [e-comm-team-amigos-bn]( https://github.com/atlp-rwanda/e-comm-team-amigos-bn)
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with `.env-example`
- Install all the dependencies by running `npm install`
- Then run the project by typing `npm start`

#### Endpoints to be tested:
- ` POST /products/add`

#### Any background context you want to provide?
- Have Node Js installed in your local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581184](https://www.pivotaltracker.com/story/show/184581184)

#### Screenshots (if appropriate)

#### Questions:

2023-03-16 17:52 UTC, GasanaJr requested changes
Update the body of your Pull request to include screenshots of passing tests and Swagger documentation.

2023-03-17 09:03 UTC, ericndungutse approved these changes
LGTM

2023-03-17 10:04 UTC, Emile-SHUMBUSHO commented on src/controllers/product.controller.js
> +    }
It's not a good practice to mix validation and create a product controller, better to handle it in middleware.

2023-03-17 10:11 UTC, Emile-SHUMBUSHO commented on src/controllers/product.controller.js
> +    res.status(400).json({ error });
Inside catch block returning status code 400(bad request) does not convince the exact the cause of error better to use status code 500(internal server error)

2023-03-17 10:39 UTC, nshutijonathan commented on src/config.js
> +    // password: process.env.DB_PASSWORD,
remove commented out codes

2023-03-17 10:40 UTC, nshutijonathan reviewed
check a few comment I left

2023-03-17 12:02 UTC, khevin2 commented on src/controllers/index.js
Please remove console.log()

2023-03-17 12:08 UTC, khevin2 approved these changes

2023-03-17 12:14 UTC, Emile-SHUMBUSHO approved these changes

2023-03-18 09:44 UTC, GasanaJr approved these changes

2023-03-20 06:51 UTC, Habinezajanvier approved these changes
👍

2023-03-20 06:51 UTC, merged