#184581188 A User Should be able to list all Items
atlp-rwanda/e-comm-team-amigos-bn pull request #26
Opened 2023-03-16 00:35 UTC by wilbrord2

#### What does this PR do?
This PR is for listing All products from Stock to the users

#### Description of Task to be completed?
-  creating routes for listing user items
- documenting routes in swagger
- test the endpoint

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm run dev
- then run npm run dev
- open postman or other testing tools you have
- create a User with role of vendor or normal
- login with the user you created
- test end point `http://localhost:4000/product/getAllItems`

#### Endpoints to be tested:
- /user/login
- /user/otp
- /product/getAllItems

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- postman (optional)

#### What are the relevant pivotal tracker/Trello stories?

Story ID: [#184581188](https://www.pivotaltracker.com/story/show/184581188)

#### Screenshots (if appropriate)

#### Questions:

2023-03-16 17:54 UTC, Habinezajanvier requested changes

2023-03-16 17:54 UTC, Habinezajanvier commented on .eslintignore
> +src/
Please add an empty line

2023-03-17 06:53 UTC, Habinezajanvier requested changes

2023-03-17 06:53 UTC, Habinezajanvier commented on src/controllers/product.controller.js
> +    });
Please don't send message in errors

2023-03-17 09:00 UTC, ericndungutse approved these changes
LGTM

2023-03-17 09:46 UTC, AbdulKhaliq59 approved these changes

2023-03-17 10:36 UTC, nshutijonathan commented on src/config.js
> +    // username: process.env.DB_USER,
get rid of commented out codes

2023-03-17 10:36 UTC, nshutijonathan commented on src/config.js
> +    // database: process.env.TEST_DB_NAME,
get rid of commented out codes

2023-03-17 10:37 UTC, nshutijonathan commented on src/controllers/product.controller.js
> +      message: error,
I would go with `message:`error.message`

2023-03-17 10:38 UTC, nshutijonathan commented on src/tests/product.test.js
> +//     await models.sequelize.sync({ force: true });
remove commented out codes

2023-03-17 10:38 UTC, nshutijonathan requested changes
Check some comments

2023-03-17 11:05 UTC, Emile-SHUMBUSHO requested changes

2023-03-17 11:05 UTC, Emile-SHUMBUSHO commented on src/controllers/product.controller.js
> +    res.status(400).json({ message: error.message });
using `error: error.message` can be more descriptive and helpful  than` message: error.message`

2023-03-17 11:33 UTC, Emile-SHUMBUSHO approved these changes

2023-03-17 11:35 UTC, Habinezajanvier requested changes

2023-03-17 11:35 UTC, Habinezajanvier commented on src/controllers/product.controller.js
> +      });
Please anything that is not sucess, I mean status code of 2XX, send `error: your error message` instead `message: error message`

2023-03-17 11:45 UTC, nshutijonathan approved these changes
LGTM

2023-03-17 12:34 UTC, Habinezajanvier approved these changes
👍

2023-03-17 12:35 UTC, merged