#184581180 Update User Profile
atlp-rwanda/e-comm-team-amigos-bn pull request #28
Opened 2023-03-16 14:36 UTC by ericndungutse

#### What does this PR do?

This PR allow user to get and update his profile. It also allow other authenticated users to get a certain user's profile

#### Description of Task to be completed?

Have the following endpoints working

- `GET /user/profile`
- `GET /user/<user_id>`
- `PATCH /user/updateMe` 

#### How should this be manually tested?

First make sure you have docker installed. In your terminal;

1. In your **e-comm-team-amigos-bn** directory, open terminal and run `git fetch origin pull/PR-ID/ft-user-profile-184581180`
2. Checkout to **ft-user-profile-184581180** branch
3. Run `npm install`
4. Run `npm run dev`
5. In postman or documentation do the following
     - Create Account / Signup
     - Use the returned token for authorizarion
     - Make requests on above mentioned endpoints.

#### Any background context you want to provide?

- Have Node Js installed in your local machine
- Should have express server running
- Should have your `.env` file with neccessary variables as in `.env.example`
     
#### What are the relevant pivotal tracker/Trello stories?

Story ID: [184581180](https://www.pivotaltracker.com/story/show/184581180)

2023-03-16 18:38 UTC, Habinezajanvier requested changes

2023-03-16 18:38 UTC, Habinezajanvier commented on src/controllers/authentication.js
>    }
Make sure that you are not sending error object, sometimes it's not formatted an meangless to the user

2023-03-16 18:38 UTC, Habinezajanvier commented on src/controllers/user.js
> +    });
Don't send message object in errors, send {error: error.message} instead

2023-03-16 18:38 UTC, Habinezajanvier commented on src/database/models/user.js
> +      verified: { type: DataTypes.BOOLEAN, defaultValue: 'false' },
Adding fields on db, make sure you add separate migrations for them

2023-03-17 08:26 UTC, wilbrord2 approved these changes

2023-03-17 10:27 UTC, nshutijonathan commented on src/database/migrations/20230316212347-updateUserRelation.js
> +// firstName: DataTypes.STRING,
commented out codes should not be pushed

2023-03-17 10:30 UTC, nshutijonathan reviewed
check comments I left

2023-03-17 10:55 UTC, Emile-SHUMBUSHO requested changes

2023-03-17 10:55 UTC, Emile-SHUMBUSHO commented on src/controllers/user.js
> +    });
how can we have status of success yet we are catching error, use message when display success result otherwise use error

2023-03-17 14:20 UTC, closed without merging

2023-03-17 15:47 UTC, ericndungutse commented
Accidentally closed.