Ft delete item 184581186
atlp-rwanda/e-comm-team-amigos-bn pull request #30
Opened 2023-03-17 07:25 UTC by Rwibutso

#### What does this PR do?
This PR will delete a specific item from a user collection

#### Description of Task to be completed?
- creating routes for delete a product 
- documenting routes in swagger
- test the endpoint

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
- /product/delete

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- postman (optional)

#### What are the relevant pivotal tracker/Trello stories?

Story ID: #184581186
#### Screenshots (if appropriate)
N/A
#### Questions:

2023-03-17 08:21 UTC, wilbrord2 reviewed
Show us the test coverage screenshot and swagger output in your endpoint documentation

2023-03-17 08:42 UTC, nshutijonathan commented on src/config.js
> +    // username: process.env.DB_USER,
Don't push commented out codes

2023-03-17 08:44 UTC, nshutijonathan requested changes
Rename your PR title

2023-03-17 10:38 UTC, Emile-SHUMBUSHO requested changes

2023-03-17 10:38 UTC, Emile-SHUMBUSHO commented on src/controllers/product.controller.js
> +    }
separate validation and controller

2023-03-17 10:38 UTC, Emile-SHUMBUSHO commented on src/controllers/product.controller.js
> +    const sellerId = decodedToken.userId;
Better to separate jwt verification and controller

2023-03-17 10:38 UTC, Emile-SHUMBUSHO commented on src/controllers/product.controller.js
> +  }
use status code 400 inside catch block is not defining exact error better to use 500 for internal sever error

2023-03-20 06:53 UTC, Emile-SHUMBUSHO commented
Rebase is required to resolve a conflicts with develop

2023-03-22 09:35 UTC, wilbrord2 reviewed
remove those conflicts

2023-03-22 10:28 UTC, nshutijonathan requested changes
LGTM

2023-03-22 10:28 UTC, nshutijonathan commented on src/app.js
> +// if (process.env.NODE_ENV === "development") {
don't push commented out codes

2023-03-22 10:28 UTC, nshutijonathan commented on src/tests/product.test.js
> +
commented out codes should not be pushed

2023-03-22 14:29 UTC, wilbrord2 approved these changes

2023-03-23 07:22 UTC, Emile-SHUMBUSHO approved these changes

2023-03-23 14:03 UTC, khevin2 approved these changes

2023-03-24 05:13 UTC, Emile-SHUMBUSHO reviewed
Cleary show documented screenshot for deleting item not deleting permission

2023-03-24 05:15 UTC, Emile-SHUMBUSHO commented
This PR has a conflict to resolve before merging it to develop

2023-03-24 09:18 UTC, AbdulKhaliq59 approved these changes
Resolve conflict and conversation unless LGTM

2023-03-25 23:18 UTC, Emile-SHUMBUSHO commented
I think permission/delete/Id was implemented in setting the user role not in the product feature.

2023-03-26 05:29 UTC, Habinezajanvier requested changes

2023-03-26 05:29 UTC, Habinezajanvier commented on src/controllers/product.controller.js
> +      const sellerId = decodedToken.userId;
Don't repeat yourself, use verifyToken middleware to extract user id and use it

2023-03-26 09:16 UTC, Habinezajanvier approved these changes
👍

2023-03-26 09:17 UTC, merged