#184581197 Get and Update order status information
atlp-rwanda/e-comm-team-amigos-bn pull request #51
Opened 2023-03-28 08:11 UTC by Mystica52

#### What does this PR do?
This PR used to get and update order status information

#### Description of Task to be completed?
- GET /order/orderStatus/:orderId
- used for getting the order status for buyer authorization
- PUT /order/orderStatus/:orderId
      used for updating the order status for admin authorization

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start

#### Endpoints to be tested:
- using  postman
- swagger documentation

#### Any background context you want to provide?
- Have Node Js installed in your local machine

#### What are the relevant pivotal tracker/Trello stories?

Story ID: 184581197

#### Screenshots (if appropriate)

2023-03-29 02:39 UTC, GasanaJr approved these changes
Looks Smooth

2023-03-29 02:46 UTC, GasanaJr requested changes
Address to the comments left.

2023-03-29 02:46 UTC, GasanaJr commented on src/app.js
> +const orderRoutes = require('./routes/order.routes');
I suggest you put this route in the designated `routes` folder instead of the `app.js`

2023-03-29 02:46 UTC, GasanaJr commented on src/controllers/order.controller.js
> +const socketIo = require('socket.io');
Change this to ES6

2023-03-29 12:50 UTC, nshutijonathan reviewed
left some comments

2023-03-29 12:50 UTC, nshutijonathan commented on src/controllers/order.controller.js
> +      message: 'Server error or token expired',
you can simply return `err.message` when you are not sure which error message

2023-03-29 12:50 UTC, nshutijonathan commented on src/controllers/order.controller.js
> +      message: 'Server error or token expired ',
I would go with `message:err.message`

2023-03-29 18:39 UTC, GasanaJr approved these changes

2023-03-30 06:56 UTC, wilbrord2 approved these changes

2023-03-30 09:36 UTC, AbdulKhaliq59 approved these changes

2023-03-30 11:40 UTC, ericndungutse approved these changes

2023-03-30 13:30 UTC, nshutijonathan approved these changes
LGTM

2023-03-30 13:31 UTC, merged