feat(order): Admin get all orders
atlp-rwanda/e-comm-team-amigos-bn pull request #58
Opened 2023-03-31 22:11 UTC by GasanaJr

#### What does this PR do?
This PR adds an admin route to get all orders.
#### Description of Task to be completed?
- creation of `admin route` to view all orders
#### How should this be manually tested?
- clone this repo `git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn`
- switch your working directory `cd e-comm-team-amigos-bn`
- create an `.env` and update it with `.env-example`
- install all dependencies by running `npm install`
- in your terminal run `npm start`
#### Test the endpoints using Postman:
- get all orders by admin`/product/admin`
#### Any background context you want to provide?
- PostgreSQL installed in your local machine
- Node JS installed in your local machine
#### What are the relevant pivotal tracker stories?
Story ID: [#184797863](https://www.pivotaltracker.com/n/projects/2632829/stories/184797863)

2023-04-01 10:31 UTC, wilbrord2 approved these changes

2023-04-01 10:44 UTC, nshutijonathan approved these changes
LGTM

2023-04-01 14:58 UTC, AbdulKhaliq59 approved these changes

2023-04-01 14:59 UTC, AbdulKhaliq59 approved these changes
resolve conflict unless It LGTM

2023-04-01 15:26 UTC, wilbrord2 commented
Can you please remove this conflicts

2023-04-03 08:08 UTC, Habinezajanvier requested changes

2023-04-03 08:08 UTC, Habinezajanvier commented on src/controllers/order.controller.js
> +    }
Check also if no order found and send a 404 status code with error message

2023-04-03 10:28 UTC, GasanaJr commented on src/controllers/order.controller.js
> +    }
It is done now

2023-04-03 15:11 UTC, merged