#184842353 Implement Newsletter Signup
atlp-rwanda/e-comm-team-amigos-bn pull request #62
Opened 2023-04-02 16:02 UTC by khevin2

#### What does this PR do?
This PR adds functionalities so that a user can
- Sign up to newsletters
- Receive email about the status of subscription by email
- Verify their email so that a user can receive periodic newsletters

#### Description of Task to be completed?
- Allow user to subscribe, unsubscribe and verify his email address to receive newsletters
- Allow admin to suspend, delete subscribers, get subscribers or by email
#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start
#### To test this PR,
- In your **e-comm-team-amigos-bn** directory, open terminal and run `git fetch origin pull/55/head:ft-newsletter-signup-184842353`
- Checkout to **ft-newsletter-signup-184842353** branch
- Run `npm install`
- Run `npm run dev`
- In your working directory terminal, run migrations and seeders. 
- Test endpoints

#### Endpoints to be tested:
- `POST /newsletter`
- `GET /newsletter/verify`
- `GET /newsletter/unsubscribe`
- `DELETE /newsletter/admin`
- `POST /newsletter/admin`
- `GET /newsletter/admin`
- `GET /newsletter/admin/{email}`

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have Postgres
- API tester like Postman

#### What are the relevant pivotal tracker?

Story ID: [#184842353](https://www.pivotaltracker.com/story/show/184842353)

#### Screenshots 

#### Questions:

2023-04-03 14:52 UTC, AbdulKhaliq59 approved these changes
LGTM

2023-04-03 14:54 UTC, Emile-SHUMBUSHO commented
file src/utils/newsletter.mail.js should not be located in utils directory according to it's serving. it's a good practice to move it into src/helpers directory.

2023-04-03 14:57 UTC, Emile-SHUMBUSHO commented
This PR miss some functionality from develop remember to rebase otherwise this PR won't be merged.

2023-04-03 15:54 UTC, GasanaJr requested changes
You have circleci fails. fix the tests

2023-04-03 16:44 UTC, Rwibutso approved these changes

2023-04-04 21:49 UTC, GasanaJr approved these changes
LGTM

2023-04-05 05:48 UTC, ericndungutse approved these changes

2023-04-05 11:41 UTC, Emile-SHUMBUSHO commented on src/utils/newsletter.mail.js
> +import path from "path";
these values seems to be not used in your codes, just remove it

2023-04-05 11:43 UTC, Emile-SHUMBUSHO approved these changes

2023-04-05 11:44 UTC, Emile-SHUMBUSHO commented
Resolve conflicts otherwise LGTM

2023-04-05 12:34 UTC, Mystica52 approved these changes

2023-04-05 12:34 UTC, Mystica52 reviewed
circle ci is failing

2023-04-05 13:18 UTC, nshutijonathan approved these changes
LGTM

2023-04-05 13:19 UTC, merged