#184581169 commit rimraf
atlp-rwanda/e-comm-team-amigos-bn pull request #9
Opened 2023-03-06 09:38 UTC by Rwibutso

#### What does this PR do?
This PR to check if rimraf can work during deployiment

#### Description of Task to be completed?
- introduce rimraf in pachage.json as dependency

#### How should this be manually tested?
- Clone this repo git clone https://github.com/atlp-rwanda/e-comm-team-amigos-bn
- Switch your working directory cd e-comm-team-amigos-bn
- Create an .env file and update it with .env-example
- Install all the dependencies by running npm install
- Then run the project by typing npm start.

#### Any background context you want to provide?
- Have Node Js installed in your local machine
- Have rimraf installed 

#### What are the relevant pivotal tracker/Trello stories?

Story ID: #184581169

#### Screenshots (if appropriate)

#### Questions:

2023-03-07 09:24 UTC, Mystica52 reviewed
delete that package-lock.json so that the conflict removed

2023-03-07 10:40 UTC, Emile-SHUMBUSHO approved these changes

2023-03-07 10:54 UTC, nshutijonathan approved these changes

2023-03-07 14:46 UTC, Habinezajanvier requested changes

2023-03-07 14:46 UTC, Habinezajanvier commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.21.0",
Please remove one package since they are the same

2023-03-07 14:50 UTC, nshutijonathan requested changes

2023-03-07 14:50 UTC, nshutijonathan commented on package.json
> +    "@babel/plugin-transform-runtime": "^7.21.0",
you do `npm uninstall @babel/plugin-transform-runtime`  
check whether `package.json` remains with one package and then push . N.B. make sure you have one commit.

2023-03-08 12:17 UTC, Habinezajanvier approved these changes
👍

2023-03-08 12:30 UTC, wilbrord2 approved these changes

2023-03-08 21:17 UTC, merged